# Generated by Django 4.0.5 on 2022-07-01 17:16

import accounts.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic_thumbnails',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=accounts.models.upload_profile_pic),
        ),
    ]
