# Generated by Django 4.0.5 on 2022-06-27 15:25

import dictionary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yiakunte_name', models.CharField(max_length=60)),
                ('english_name', models.CharField(max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to=dictionary.models.upload_category_image)),
                ('voice', models.FileField(blank=True, null=True, upload_to=dictionary.models.upload_category_audio)),
                ('verified', models.BooleanField(default=False)),
                ('verify_count', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.category')),
            ],
        ),
    ]
